### ISSUE TITLE
"Copy Code" buttons should self-initialize

### ISSUE THREAD

**Issue by hirasso** [expressive-code/expressive-code#16]
I'm testing `astro-expressive-code` on one of my sites. That site is set up so that it doesn't do hard browser reloads but rather provides an SPA experience. 

- When I visit one of my pages that contain code blocks directly, the "Copy Code" button works as expected
- When I navigate to one of those pages from within my site, the buttons are rendered but don't do anything

I think this would be a very good use case for a self-initializing web component? Alternatively, exposing an API to manually re-initialize the buttons would also be fine.

I got a bit lost while source diving, but it should happen somewhere here I guess: https://github.com/expressive-code/expressive-code/blob/main/packages/%40expressive-code/plugin-frames/src/copy-js-module.ts

**Comment by hippotastic** [comment]
Hello @hirasso - thank you very much for testing Expressive Code and submitting this issue!

You're right, I didn't think of SPA scenarios yet. Time to change that!

The file you linked is indeed the one we need to modify. My idea would be to extract the inline function `(button) => button.addEventListener('click', async () => { ... })` to a variable like `addHandler` and both call it once in `document.querySelectorAll('[SELECTOR]').forEach(addHandler)`, add then register a `MutationObserver` that catches new elements matching the selector and also calls `addHandler` on them.

Do you think that would work for your SPA scenario? Do you want to give it a shot at implementing this or should I?

Also, to verify that our upcoming fix works, it would be helpful if you could share a bit more about how you've added SPA to your site. Are you using an integration like `astro-spa` for that?

**Comment by hirasso** [comment]
Hey @hippotastic !

a `MutationObserver` sounds like a possible solution, even though I very much like the self-initializing nature of [custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements). Something like `<ec-copy-button>` or the like. Anyhow, I know that custom elements come with their own set of complexities and I'm a fan of simple solutions, AND – who cares about implementation details anyways? 😄

> Do you think that would work for your SPA scenario? 

Yes!

>  Do you want to give it a shot at implementing this or should I?

I'm a bit intimidated by that code and pretty busy at the moment, so I would gladly hand the implementation over to you ☺️ 

> Also, to verify that our upcoming fix works, it would be helpful if you could share a bit more about how you've added SPA to your site. Are you using an integration like astro-spa for that?

I'm using [swup](https://swup.js.org/) for the SPA-ization. (Fun fact: I'm a maintainer of that library and we are currently building an astro integration: https://github.com/swup/astro)

The site I'm currently working on is a demo for an upcoming [swup plugin](https://github.com/swup/fragment-plugin) we are developing (that's why I'm so busy 😉), that will bring route-based fragments to MPAs. You are [welcome to check out the demo](https://swup-fragment-plugin.netlify.app/)!

Actually, that's where you can even see the current behavior of the copy button, when you navigate directly to [/how-it-works](https://swup-fragment-plugin.netlify.app/how-it-works/) (the buttons work), then navigate to the front page and back to /how-it-works (the buttons don't work anymore).

**Comment by hippotastic** [comment]
Thank you for providing all of this helpful information!

The demo you linked looks amazing, I love the page transitions. Really happy to hear you're developing an Astro plugin, too!

I have implemented the fix we discussed that should hopefully solve the SPA issue. I also like the concept of custom elements, but haven't used them in production yet, so in order to get the fix working soon, I chose the `MutationObserver` path for now.

I have just pushed new releases to NPM. Could you please update your dependencies to these latest versions and have a look if this fixes the SPA issue for you?

```
🦋  @expressive-code/plugin-frames@0.10.1
🦋  astro-expressive-code@0.12.2
🦋  expressive-code@0.12.2
🦋  remark-expressive-code@0.12.2
```

**Comment by hirasso** [comment]
I just installed `0.12.2` to test the copy buttons. I'm getting an error on compile time:

> Plugin "Shiki" caused an error in its "performSyntaxAnalysis" hook. Error message: Expected a valid instance of ExpressiveCodeAnnotation, but got {"inlineRange":{"columnStart":0,"columnEnd":3},"color":"#B392F0","italic":false,"bold":false,"underline":false}

**Comment by hirasso** [comment]
Weird – I tried downgrading `astro-expressive-code` to `0.12.1` but the above error persists. Even a clean install of `node_modules` doesn't fix it.

**Comment by hippotastic** [comment]
That sounds strange indeed, maybe a package version mismatch?

Can you share your `package.json`, or maybe even better a reproduction or link to a repo/PR so I can test it myself?

**Comment by hippotastic** [comment]
Found the issue! It was indeed a package version mismatch. If you install the latest astro-expressive-code version (0.14.0 at the time of writing this), the error is gone.

**Comment by hirasso** [comment]
Tested it, works like a charm now! 🥳

**Comment by yaralahruthik** [comment]
@hippotastic 

I think this issue is still prevalent.

For example, if you have something like Tabs and the first tab does not have any code block but the second one does. The copy module is not loaded. The fix is to forceMount the tabs always. I might be doing something wrong too. Will share a reproducible version as soon as I find time.

![image](https://github.com/user-attachments/assets/a3a1a43b-d22f-4367-a210-3baae76ad8ba)

**Comment by hippotastic** [comment]
> I think this issue is still prevalent.
> 
> For example, if you have something like Tabs and the first tab does not have any code block but the second one does. The copy module is not loaded. The fix is to forceMount the tabs always. I might be doing something wrong too. Will share a reproducible version as soon as I find time.

The problem with hosting Expressive Code blocks inside framework component tabs that don't even mount their contents into the DOM when not visible is unfortunately hard to solve. Due to not being included in the DOM by default, the statically prerendered version of the component does not include the script module, so the browser doesn't know about it when first navigating to this page and won't load it.

An alternate workaround (besides always mounting the tab contents) is to add a single code block somewhere in your shared layout (that can even be set to `display: none` through CSS). This will cause the script module and styles to always be loaded and therefore the issue should disappear.

**Comment by yaralahruthik** [comment]
@hippotastic That was fast. Yep, pretty much using the same hacky solution. Thanks for the quick response!

**Comment by hippotastic** [comment]
Do I correctly assume from your screenshot that you're using `astro-expressive-code`? To avoid loading the JS modules on pages that don't have any code blocks (e.g. a performance-critical landing page), this package only adds links to its JS modules and stylesheets to pages that include at least one code block (...in the statically prerendered version of the page - I can't access other versions that rely on interaction from my package).

I could imagine addding an option to disable this performance-focused mode and have the package always add its JS modules and stylesheets, even if no code blocks were detected on a page. This could be a possible future solution in case the other approaches are not acceptable to you. Let me know what you think!

**Comment by yaralahruthik** [comment]
> Do I correctly assume from your screenshot that you're using `astro-expressive-code`? To avoid loading the JS modules on pages that don't have any code blocks (e.g. a performance-critical landing page), this package only adds links to its JS modules and stylesheets to pages that include at least one code block (...in the statically prerendered version of the page - I can't access other versions that rely on interaction from my package).

Yes! Oh, did not know about this performance thing.

> I could imagine addding an option to disable this performance-focused mode and have the package always add its JS modules and stylesheets, even if no code blocks were detected on a page. This could be a possible future solution in case the other approaches are not acceptable to you. Let me know what you think!

Hmm, I assume most folks who use this package pretty much need those code blocks everywhere on the site. So, this option might be super useful. But I am more than happy to use a hacky solution.
